### PR TITLE
feat: general backend

### PR DESCRIPTION
**Pull request by xhebox**
Main changes:

1. Duplicated `kernel_opt.h` and `kernel_opt.cpp` into every platform (x86/arm)
2. Use cmake to control whether compile `src/kern/optimized/${arch}` or `src/kern/gpu`
3. Remove platform macros like `ifdef INFER_XXX` in `src/kern/optimized/${arch}`

This allows more flexiblity in platform implementation. I mean that every arch can implement different kernels. You don't need to write every kernel in `kernel_opt.h`. You can also write some kernels if you like.

For example, for rvv arch, you don't need to write vectorized cpp code for compilers. That does not quite work on rvv.

### CODE REVIEW

**Comment by chenqy4933** [comment]
👍

**Comment by xhebox** [comment]
Thanks for the invitation, so, does this PR LGTM to you? @chenqy4933

**Comment by chenqy4933** [comment]
make local there are error:
```
/tmp/cclkOYZK.s:39948: Error: symbol `_ZZN8inferllm3opt24vec_vec_dot_q40_with_q80EiPKvS2_E19__PRETTY_FUNCTION__' is already defined
/tmp/cclkOYZK.s:39953: Error: symbol `_ZZN8inferllm3opt24vec_vec_dot_q40_with_q80EiPKvS2_E19__PRETTY_FUNCTION__' is already defined
/tmp/cclkOYZK.s:39983: Error: symbol `_ZZN8inferllm3opt19dequantize_row_q4_0EPKvPfiE19__PRETTY_FUNCTION__' is already defined
```

**Comment by xhebox** [comment]
> make local there are error:
> 
> ```
> /tmp/cclkOYZK.s:39948: Error: symbol `_ZZN8inferllm3opt24vec_vec_dot_q40_with_q80EiPKvS2_E19__PRETTY_FUNCTION__' is already defined
> /tmp/cclkOYZK.s:39953: Error: symbol `_ZZN8inferllm3opt24vec_vec_dot_q40_with_q80EiPKvS2_E19__PRETTY_FUNCTION__' is already defined
> /tmp/cclkOYZK.s:39983: Error: symbol `_ZZN8inferllm3opt19dequantize_row_q4_0EPKvPfiE19__PRETTY_FUNCTION__' is already defined
> ```

I'll check later.

**Comment by xhebox** [comment]
> make local there are error:
> 
> ```
> /tmp/cclkOYZK.s:39948: Error: symbol `_ZZN8inferllm3opt24vec_vec_dot_q40_with_q80EiPKvS2_E19__PRETTY_FUNCTION__' is already defined
> /tmp/cclkOYZK.s:39953: Error: symbol `_ZZN8inferllm3opt24vec_vec_dot_q40_with_q80EiPKvS2_E19__PRETTY_FUNCTION__' is already defined
> /tmp/cclkOYZK.s:39983: Error: symbol `_ZZN8inferllm3opt19dequantize_row_q4_0EPKvPfiE19__PRETTY_FUNCTION__' is already defined
> ```

@chenqy4933 Can you provide me some more info? For example, the output of cmake, with the following lines inserted at L61

```
message(STATUS "${INFER_ARCH}")
message(STATUS "${SRC}")
message(STATUS "${PLTSRC}")
````

**Comment by xhebox** [comment]
> it is right，I test on other x86 machine。the log is:

Hmm, this is strange. Can you paste your full log with `cmake --build build -v`? Just paste it to https://pastebin.com/ or somewhere else. I can't reproduce.

**Comment by chenqy4933** [comment]
I will debug it in my machine， LGTM

**Pull request merged**
